services:
  web_a:
    image: odoo:17
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-a-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=openpg
      - PASSWORD=openpgpwd
    networks:
      - odoo-network
    restart: unless-stopped

  web_b:
    image: odoo:17
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-b-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=openpg
      - PASSWORD=openpgpwd
    networks:
      - odoo-network
    restart: unless-stopped

  db:
    image: postgres:15
    user: "0:0"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=openpgpwd
      - POSTGRES_USER=openpg
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openpg -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.0.0
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - odoo-network
    restart: unless-stopped

volumes:
  odoo-web-a-data:
  odoo-web-b-data:
  odoo-db-data:
  pgadmin-data:

networks:
  odoo-network:
    name: odoo-network
    driver: bridge
